## LinearAlgebra
### Laboratory 7 : Matrix Operations

Coded and Submitted by:<br>
Embuscado Khayle Anthony L. 

### Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy

In [2]:
import numpy as np 

In [3]:
x = np.array([
    [7 ,6,5],
    [1, 0,2],
    [3,1, 0]
])
y = np.array([
    [-2 ,-3,-1],
    [-7, -8,-4], 
    [-1, -2,-5]
])
z = np.array([
    [2 ,1,2],
    [-2, -2,-2], 
    [0,-1,3]
])
print(x.shape)
print(y.shape)
print(z.shape)

(3, 3)
(3, 3)
(3, 3)


1. $x\cdot y \neq x \cdot y$

In [7]:
np.dot(x,y)

array([[-61, -79, -56],
       [ -4,  -7, -11],
       [-13, -17,  -7]])

In [8]:
np.dot(y,x)

array([[-20, -13, -16],
       [-69, -46, -51],
       [-24, -11,  -9]])

In [9]:
np.array_equiv(x.dot(y), y.dot(x))

False

2. $x \cdot (y \cdot z) = (x \cdot y) \cdot z$

In [10]:
x @ (y @ z)

array([[  36,  153, -132],
       [   6,   21,  -27],
       [   8,   28,  -13]])

In [11]:
(x@y) @ z

array([[  36,  153, -132],
       [   6,   21,  -27],
       [   8,   28,  -13]])

In [12]:
np.array_equiv((x @ (y @ z)),((x @ y) @z))

True

3. $x\cdot(y+z) = x\cdot y + x\cdot z$

In [13]:
np.dot((y+z), x)

array([[  1,   1,  -4],
       [-91, -60, -65],
       [-16,  -8, -11]])

In [14]:
y.dot(x) + z.dot(x)

array([[  1,   1,  -4],
       [-91, -60, -65],
       [-16,  -8, -11]])

In [15]:
np.array_equiv((y+z).dot(x), y.dot(x)+z.dot(x))

True

5. $x\cdot I \neq x$

In [19]:
I= np.array(x.dot(np.linalg.inv(x)), dtype=int)
I

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [20]:
x.dot(I)

array([[7, 0, 5],
       [1, 0, 2],
       [3, 0, 0]])

In [18]:
np.array_equal(x.dot(I), x)

False

6. $x\cdot \emptyset = \emptyset$

In [21]:
null= x.dot(np.zeros(x.shape))
null

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zero = np.zeros(x.shape)
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(null,zero)